---
- hosts: all-nodes
  gather_facts: no
  become: true
  remote_user: ansible
  vars:
    cluster_name: test
    seeds: 52.14.159.203,52.14.108.53,54.202.57.109,54.149.126.26
    aws_meta: http://169.254.169.254/latest/meta-data
    bind_ip: "{{aws_meta}}/local-ipv4"
    broadcast_ip: "{{aws_meta}}/public-ipv4"

  tasks:

  - name : "Copy template"
    copy:
      src: ../resources/opt/cassandra/conf/cassandra-yaml.template
      dest: /opt/cassandra/conf/cassandra-yaml.template
      owner: cassandra
      group: cassandra
      mode: "u=rw,g=r,o=r"

  - name : "Get bind_ip"
    command: curl {{bind_ip}}
    register: bind_ip_contents

  - name : "Get broadcast_ip"
    command: curl {{broadcast_ip}}
    register: broadcast_ip_contents

  - name: Configure Cassandra
    command: "/opt/cloudurable/bin/cassandra-cloud -cluster-name  {{cluster_name}} \
                              -client-address  {{bind_ip_contents.stdout}} \
                              -cluster-address  {{bind_ip_contents.stdout}} \
                              -cluster-seeds {{seeds}} \
                              -cluster-broadcast-address {{broadcast_ip_contents.stdout}} \
                              -snitch Ec2MultiRegionSnitch"

  - name: Restart Cassandra
    command: "/bin/systemctl restart  cassandra"



#    region: "{{aws_meta}}/placement/availability-zone"
#  - name : "Get region"
#    shell: curl {{region}} | cut -c 1-9
#    register: region_contents
#  - name : "Copy correct rackdc"
#    copy:
#      src: "../resources/opt/cassandra/conf/cassandra-rackdc-{{region_contents.stdout}}.properties"
#      dest: "/opt/cassandra/conf/cassandra-rackdc.properties"
#      owner: cassandra
#      group: cassandra
#      mode: "u=rw,g=r,o=r"